FROM python:3.11-slim

WORKDIR /app

# solo lo necesario
COPY requirements.txt .

RUN pip install --no-cache-dir streamlit requests pillow

# copiar solo frontend
COPY app ./app

EXPOSE 8501

CMD ["streamlit", "run", "app/streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]