version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: caida-detector-api

    ports:
      - "8080:8080"

    volumes:
      - ./src:/app/src
      - ./models:/app/models
      - ./metrics.json:/app/metrics.json

    environment:
      - PYTHONUNBUFFERED=1
      - MODEL_PATH=/app/models/resnet18.pth   # podriamos utilizar usamos el optimizado

    restart: unless-stopped

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit

    container_name: caida-detector-ui

    ports:
      - "8501:8501"

    volumes:
      - ./app:/app/app

    environment:
      - PYTHONUNBUFFERED=1

    depends_on:
      - fastapi

    restart: unless-stopped
